services:
  node-installer:
    image: node:22.15.0
    volumes:
      - ./:/home/node/project
    environment:
      npm_config_cache: /home/node/cache
    working_dir: /home/node/project
    user: 1000:1000
    command: npm i

  vue:
    image: node:22.15.0
    container_name: portfolio-vue
    volumes:
      - ./:/home/node/project
    environment:
      npm_config_cache: /home/node/cache
    working_dir: /home/node/project
    ports:
      - 3000:3000
    user: 1000:1000
    command: npm run dev:vue
    depends_on:
      node-installer:
        condition: service_completed_successfully

  duplo:
    image: node:22.15.0
    container_name: portfolio-duplo
    volumes:
      - ./:/home/node/project
    environment:
      npm_config_cache: /home/node/cache
    working_dir: /home/node/project
    ports:
      - 1506:1506
    user: 1000:1000
    command: npm run dev:duplo
    depends_on:
      node-installer:
        condition: service_completed_successfully
