// Generated by @duplojs/types-codegen
/* eslint-disable */
/* prettier-ignore */
/* istanbul ignore file */
/* v8 ignore start */
// noinspection JSUnusedGlobalSymbols
// @ts-nocheck
type CodegenRoutes = ({
    method: "POST";
    path: "/authentication";
    body: {
        email: string;
        password: string;
    };
    response: {
        code: 404;
        information: "user.notfound";
        body?: undefined;
    } | {
        code: 401;
        information: "user.invalid.password";
        body?: undefined;
    } | {
        code: 200;
        information: "user.logged";
        body: string;
    };
}) | ({
    method: "PATCH";
    path: "/projects/{projectId}";
    body: {
        fields: {
            status: "Published" | "Unpublished";
        };
    };
    params: {
        projectId: string;
    };
    response: {
        code: 404;
        information: "project.notfound";
        body?: undefined;
    } | {
        code: 200;
        information: "project.updated";
        body: {
            id: string;
            fields: {
                title: string;
                status: "Published" | "Unpublished";
                nbLikes: number;
            };
            createdTime: string;
        };
    };
}) | ({
    method: "GET";
    path: "/projects/{projectId}";
    params: {
        projectId: string;
    };
    response: {
        code: 404;
        information: "project.notfound";
        body?: undefined;
    } | {
        code: 200;
        information: "project.found";
        body: {
            id: string;
            fields: {
                title: string;
                status: "Published" | "Unpublished";
                nbLikes: number;
            };
            createdTime: string;
        };
    };
});

export { CodegenRoutes };
/* v8 ignore stop */
